//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRP_BS_SEQ
    {
        public string TABLE_NA { get; set; }
        public string PK_YYYY { get; set; }
        public string PK_MM { get; set; }
        public string PK_DD { get; set; }
        public string PK_STR1 { get; set; }
        public Nullable<short> CURRENT_SEQ { get; set; }
        public Nullable<System.DateTime> MOD_UTC { get; set; }
    }
}
