//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRPCUST
    {
        public GRPCUST()
        {
            this.GRPCONTACT = new HashSet<GRPCONTACT>();
        }
    
        public string CUST_ID { get; set; }
        public string CUST_NO { get; set; }
        public string CUST_NAME { get; set; }
        public string PHONE_NUM { get; set; }
    
        public virtual ICollection<GRPCONTACT> GRPCONTACT { get; set; }
    }
}
