//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP0002
    {
        public int MP0002_SEQ { get; set; }
        public string MP0002_DEPARTMENT_NUM { get; set; }
        public string MP0002_DEPARTMENT_NAME { get; set; }
        public string MP0002_DEPARTMENT_DESC { get; set; }
        public string MP0002_DEPARTMENT_STATUS { get; set; }
        public string MP0002_CREATE_USER { get; set; }
        public Nullable<System.DateTime> MP0002_CREATE_DATETIME { get; set; }
        public string MP0002_EDIT_USER { get; set; }
        public Nullable<System.DateTime> MP0002_EDIT_DATETIME { get; set; }
    }
}
