//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP1001
    {
        public string MP1001_EMPLOYEE_NUM { get; set; }
        public string MP1001_EMPLOYEE_ID { get; set; }
        public string MP1001_SURNAME { get; set; }
        public string MP1001_FIRSTNAME { get; set; }
        public string MP1001_PREFERED_NAME { get; set; }
        public string MP1001_VISA_TYPE { get; set; }
        public string MP1001_DEPARTMENT_ID { get; set; }
        public string MP1001_POSITION { get; set; }
        public string MP1001_GENDER { get; set; }
        public string MP1001_RELIGION { get; set; }
        public string MP1001_NATIONALITY { get; set; }
        public Nullable<System.DateTime> MP1001_BIRTHDAY { get; set; }
        public string MP1001_MARRIAGE_STATUS { get; set; }
        public string MP1001_RACE { get; set; }
        public string MP1001_MOBILE_PHONE { get; set; }
        public string MP1001_TELEPHONE { get; set; }
        public string MP1001_OTHER_CONTACT { get; set; }
        public string MP1001_EMAIL { get; set; }
        public string MP1001_COMPANY_EMAIL { get; set; }
        public string MP1001_DEGREE_LEVEL { get; set; }
        public Nullable<System.DateTime> MP1001_ENTRY_DATE { get; set; }
        public string MP1001_STATUS { get; set; }
        public string MP1001_ANNUAL_STATUS { get; set; }
        public Nullable<System.DateTime> MP1001_RESIGN_DATE { get; set; }
        public string MP1001_RESIGN_REASON { get; set; }
        public string MP1001_RESIGN_TYPE { get; set; }
        public byte[] MP1001_PICTURE { get; set; }
        public string MP1001_PICTURE_NAME { get; set; }
        public string MP1001_PHYSICAL_ADDRESS { get; set; }
        public string MP1001_PASSWORD { get; set; }
        public Nullable<System.DateTime> MP1001_PASSWORD_DATE { get; set; }
        public string MP1001_GROUP { get; set; }
        public string MP1001_RECTIFY_TIMES { get; set; }
        public Nullable<int> MP1001_FREE_MONEY { get; set; }
        public Nullable<System.DateTime> MP1001_CHG_TIME { get; set; }
        public string MP1001_CHG_EMPLOYE { get; set; }
        public string MP1001_CREATE_USER { get; set; }
        public Nullable<System.DateTime> MP1001_CREATE_DATE { get; set; }
        public string MP1001_EDIT_USER { get; set; }
        public Nullable<System.DateTime> MP1001_EDIT_DATE { get; set; }
    }
}
