//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PrudenceERPEntities3 : DbContext
    {
        public PrudenceERPEntities3()
            : base("name=PrudenceERPEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GRP_BS_SEQ> GRP_BS_SEQ { get; set; }
        public virtual DbSet<GRP_BS_SPMRK> GRP_BS_SPMRK { get; set; }
        public virtual DbSet<GRP_BS_WHE> GRP_BS_WHE { get; set; }
        public virtual DbSet<GRPMAD> GRPMAD { get; set; }
        public virtual DbSet<GRPMAH> GRPMAH { get; set; }
        public virtual DbSet<GRPREC> GRPREC { get; set; }
        public virtual DbSet<GRPREC_PRT> GRPREC_PRT { get; set; }
        public virtual DbSet<SYSCKIND> SYSCKIND { get; set; }
        public virtual DbSet<SYSCODE> SYSCODE { get; set; }
        public virtual DbSet<SYSCOMP> SYSCOMP { get; set; }
        public virtual DbSet<SYSDEPT> SYSDEPT { get; set; }
        public virtual DbSet<SYSPACK> SYSPACK { get; set; }
        public virtual DbSet<SYSPRG> SYSPRG { get; set; }
        public virtual DbSet<SYSROLE> SYSROLE { get; set; }
        public virtual DbSet<SYSROLE_FUN> SYSROLE_FUN { get; set; }
        public virtual DbSet<SYSUSER> SYSUSER { get; set; }
        public virtual DbSet<MP0002> MP0002 { get; set; }
        public virtual DbSet<MP1001> MP1001 { get; set; }
        public virtual DbSet<vwSYSPRG_MENU> vwSYSPRG_MENU { get; set; }
    
        public virtual int aDevTool_新增程式基本檔(ObjectParameter pRG_NO, string pRG_NAME, string pRG_TYPE, string pRG_AREA, string mVC_CTRL, string mVC_ACT, string eNT_POINT, string pARAM_VAL, string iS_MENU, string uP_DIRNO)
        {
            var pRG_NAMEParameter = pRG_NAME != null ?
                new ObjectParameter("PRG_NAME", pRG_NAME) :
                new ObjectParameter("PRG_NAME", typeof(string));
    
            var pRG_TYPEParameter = pRG_TYPE != null ?
                new ObjectParameter("PRG_TYPE", pRG_TYPE) :
                new ObjectParameter("PRG_TYPE", typeof(string));
    
            var pRG_AREAParameter = pRG_AREA != null ?
                new ObjectParameter("PRG_AREA", pRG_AREA) :
                new ObjectParameter("PRG_AREA", typeof(string));
    
            var mVC_CTRLParameter = mVC_CTRL != null ?
                new ObjectParameter("MVC_CTRL", mVC_CTRL) :
                new ObjectParameter("MVC_CTRL", typeof(string));
    
            var mVC_ACTParameter = mVC_ACT != null ?
                new ObjectParameter("MVC_ACT", mVC_ACT) :
                new ObjectParameter("MVC_ACT", typeof(string));
    
            var eNT_POINTParameter = eNT_POINT != null ?
                new ObjectParameter("ENT_POINT", eNT_POINT) :
                new ObjectParameter("ENT_POINT", typeof(string));
    
            var pARAM_VALParameter = pARAM_VAL != null ?
                new ObjectParameter("PARAM_VAL", pARAM_VAL) :
                new ObjectParameter("PARAM_VAL", typeof(string));
    
            var iS_MENUParameter = iS_MENU != null ?
                new ObjectParameter("IS_MENU", iS_MENU) :
                new ObjectParameter("IS_MENU", typeof(string));
    
            var uP_DIRNOParameter = uP_DIRNO != null ?
                new ObjectParameter("UP_DIRNO", uP_DIRNO) :
                new ObjectParameter("UP_DIRNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("aDevTool_新增程式基本檔", pRG_NO, pRG_NAMEParameter, pRG_TYPEParameter, pRG_AREAParameter, mVC_CTRLParameter, mVC_ACTParameter, eNT_POINTParameter, pARAM_VALParameter, iS_MENUParameter, uP_DIRNOParameter);
        }
    
        public virtual int aDevTool_新增程式基本檔_Single(string pRG_NAME, string pRG_TYPE, string pRG_AREA, string mVC_CTRL, string mVC_ACT, string eNT_POINT, string pARAM_VAL, string iS_MENU, string uP_DIRNO)
        {
            var pRG_NAMEParameter = pRG_NAME != null ?
                new ObjectParameter("PRG_NAME", pRG_NAME) :
                new ObjectParameter("PRG_NAME", typeof(string));
    
            var pRG_TYPEParameter = pRG_TYPE != null ?
                new ObjectParameter("PRG_TYPE", pRG_TYPE) :
                new ObjectParameter("PRG_TYPE", typeof(string));
    
            var pRG_AREAParameter = pRG_AREA != null ?
                new ObjectParameter("PRG_AREA", pRG_AREA) :
                new ObjectParameter("PRG_AREA", typeof(string));
    
            var mVC_CTRLParameter = mVC_CTRL != null ?
                new ObjectParameter("MVC_CTRL", mVC_CTRL) :
                new ObjectParameter("MVC_CTRL", typeof(string));
    
            var mVC_ACTParameter = mVC_ACT != null ?
                new ObjectParameter("MVC_ACT", mVC_ACT) :
                new ObjectParameter("MVC_ACT", typeof(string));
    
            var eNT_POINTParameter = eNT_POINT != null ?
                new ObjectParameter("ENT_POINT", eNT_POINT) :
                new ObjectParameter("ENT_POINT", typeof(string));
    
            var pARAM_VALParameter = pARAM_VAL != null ?
                new ObjectParameter("PARAM_VAL", pARAM_VAL) :
                new ObjectParameter("PARAM_VAL", typeof(string));
    
            var iS_MENUParameter = iS_MENU != null ?
                new ObjectParameter("IS_MENU", iS_MENU) :
                new ObjectParameter("IS_MENU", typeof(string));
    
            var uP_DIRNOParameter = uP_DIRNO != null ?
                new ObjectParameter("UP_DIRNO", uP_DIRNO) :
                new ObjectParameter("UP_DIRNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("aDevTool_新增程式基本檔_Single", pRG_NAMEParameter, pRG_TYPEParameter, pRG_AREAParameter, mVC_CTRLParameter, mVC_ACTParameter, eNT_POINTParameter, pARAM_VALParameter, iS_MENUParameter, uP_DIRNOParameter);
        }
    
        public virtual int GRP_0_AddReciveForm(ObjectParameter rEC_ID, string rEC_MNO, Nullable<System.DateTime> rECIN_UTC, string dISPATCH, string dISPATCH_CON, string rECEIVING, string rECEIVING_CON, string dEST_NAME, string gOODS_NAME, Nullable<int> qTY, Nullable<decimal> qTY_WEIGHT, Nullable<decimal> qTY_VOLUME, Nullable<int> qTY_NUMBER, string rEMARK, string cRT_USER)
        {
            var rEC_MNOParameter = rEC_MNO != null ?
                new ObjectParameter("REC_MNO", rEC_MNO) :
                new ObjectParameter("REC_MNO", typeof(string));
    
            var rECIN_UTCParameter = rECIN_UTC.HasValue ?
                new ObjectParameter("RECIN_UTC", rECIN_UTC) :
                new ObjectParameter("RECIN_UTC", typeof(System.DateTime));
    
            var dISPATCHParameter = dISPATCH != null ?
                new ObjectParameter("DISPATCH", dISPATCH) :
                new ObjectParameter("DISPATCH", typeof(string));
    
            var dISPATCH_CONParameter = dISPATCH_CON != null ?
                new ObjectParameter("DISPATCH_CON", dISPATCH_CON) :
                new ObjectParameter("DISPATCH_CON", typeof(string));
    
            var rECEIVINGParameter = rECEIVING != null ?
                new ObjectParameter("RECEIVING", rECEIVING) :
                new ObjectParameter("RECEIVING", typeof(string));
    
            var rECEIVING_CONParameter = rECEIVING_CON != null ?
                new ObjectParameter("RECEIVING_CON", rECEIVING_CON) :
                new ObjectParameter("RECEIVING_CON", typeof(string));
    
            var dEST_NAMEParameter = dEST_NAME != null ?
                new ObjectParameter("DEST_NAME", dEST_NAME) :
                new ObjectParameter("DEST_NAME", typeof(string));
    
            var gOODS_NAMEParameter = gOODS_NAME != null ?
                new ObjectParameter("GOODS_NAME", gOODS_NAME) :
                new ObjectParameter("GOODS_NAME", typeof(string));
    
            var qTYParameter = qTY.HasValue ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(int));
    
            var qTY_WEIGHTParameter = qTY_WEIGHT.HasValue ?
                new ObjectParameter("QTY_WEIGHT", qTY_WEIGHT) :
                new ObjectParameter("QTY_WEIGHT", typeof(decimal));
    
            var qTY_VOLUMEParameter = qTY_VOLUME.HasValue ?
                new ObjectParameter("QTY_VOLUME", qTY_VOLUME) :
                new ObjectParameter("QTY_VOLUME", typeof(decimal));
    
            var qTY_NUMBERParameter = qTY_NUMBER.HasValue ?
                new ObjectParameter("QTY_NUMBER", qTY_NUMBER) :
                new ObjectParameter("QTY_NUMBER", typeof(int));
    
            var rEMARKParameter = rEMARK != null ?
                new ObjectParameter("REMARK", rEMARK) :
                new ObjectParameter("REMARK", typeof(string));
    
            var cRT_USERParameter = cRT_USER != null ?
                new ObjectParameter("CRT_USER", cRT_USER) :
                new ObjectParameter("CRT_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_0_AddReciveForm", rEC_ID, rEC_MNOParameter, rECIN_UTCParameter, dISPATCHParameter, dISPATCH_CONParameter, rECEIVINGParameter, rECEIVING_CONParameter, dEST_NAMEParameter, gOODS_NAMEParameter, qTYParameter, qTY_WEIGHTParameter, qTY_VOLUMEParameter, qTY_NUMBERParameter, rEMARKParameter, cRT_USERParameter);
        }
    
        public virtual int GRP_AddReciveForm(string rEC_MNO, Nullable<System.DateTime> rECIN_UTC, string dISPATCH, string dISPATCH_CON, string rECEIVING, string rECEIVING_CON, string dEST_NAME, string gOODS_NAME, Nullable<int> qTY, Nullable<decimal> qTY_WEIGHT, Nullable<decimal> qTY_VOLUME, Nullable<int> qTY_NUMBER, string rEMARK, string cRT_USER)
        {
            var rEC_MNOParameter = rEC_MNO != null ?
                new ObjectParameter("REC_MNO", rEC_MNO) :
                new ObjectParameter("REC_MNO", typeof(string));
    
            var rECIN_UTCParameter = rECIN_UTC.HasValue ?
                new ObjectParameter("RECIN_UTC", rECIN_UTC) :
                new ObjectParameter("RECIN_UTC", typeof(System.DateTime));
    
            var dISPATCHParameter = dISPATCH != null ?
                new ObjectParameter("DISPATCH", dISPATCH) :
                new ObjectParameter("DISPATCH", typeof(string));
    
            var dISPATCH_CONParameter = dISPATCH_CON != null ?
                new ObjectParameter("DISPATCH_CON", dISPATCH_CON) :
                new ObjectParameter("DISPATCH_CON", typeof(string));
    
            var rECEIVINGParameter = rECEIVING != null ?
                new ObjectParameter("RECEIVING", rECEIVING) :
                new ObjectParameter("RECEIVING", typeof(string));
    
            var rECEIVING_CONParameter = rECEIVING_CON != null ?
                new ObjectParameter("RECEIVING_CON", rECEIVING_CON) :
                new ObjectParameter("RECEIVING_CON", typeof(string));
    
            var dEST_NAMEParameter = dEST_NAME != null ?
                new ObjectParameter("DEST_NAME", dEST_NAME) :
                new ObjectParameter("DEST_NAME", typeof(string));
    
            var gOODS_NAMEParameter = gOODS_NAME != null ?
                new ObjectParameter("GOODS_NAME", gOODS_NAME) :
                new ObjectParameter("GOODS_NAME", typeof(string));
    
            var qTYParameter = qTY.HasValue ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(int));
    
            var qTY_WEIGHTParameter = qTY_WEIGHT.HasValue ?
                new ObjectParameter("QTY_WEIGHT", qTY_WEIGHT) :
                new ObjectParameter("QTY_WEIGHT", typeof(decimal));
    
            var qTY_VOLUMEParameter = qTY_VOLUME.HasValue ?
                new ObjectParameter("QTY_VOLUME", qTY_VOLUME) :
                new ObjectParameter("QTY_VOLUME", typeof(decimal));
    
            var qTY_NUMBERParameter = qTY_NUMBER.HasValue ?
                new ObjectParameter("QTY_NUMBER", qTY_NUMBER) :
                new ObjectParameter("QTY_NUMBER", typeof(int));
    
            var rEMARKParameter = rEMARK != null ?
                new ObjectParameter("REMARK", rEMARK) :
                new ObjectParameter("REMARK", typeof(string));
    
            var cRT_USERParameter = cRT_USER != null ?
                new ObjectParameter("CRT_USER", cRT_USER) :
                new ObjectParameter("CRT_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_AddReciveForm", rEC_MNOParameter, rECIN_UTCParameter, dISPATCHParameter, dISPATCH_CONParameter, rECEIVINGParameter, rECEIVING_CONParameter, dEST_NAMEParameter, gOODS_NAMEParameter, qTYParameter, qTY_WEIGHTParameter, qTY_VOLUMEParameter, qTY_NUMBERParameter, rEMARKParameter, cRT_USERParameter);
        }
    
        public virtual int GRP_AddReciveForm2(string rEC_MNO, Nullable<System.DateTime> rECIN_UTC, string dISPATCH, string dISPATCH_CON, string rECEIVING, string rECEIVING_CON, string dEST_NAME, string gOODS_NAME, Nullable<int> qTY, Nullable<decimal> qTY_WEIGHT, Nullable<decimal> qTY_VOLUME, Nullable<int> qTY_NUMBER, string rEMARK, string cRT_USER, Nullable<bool> directPrint)
        {
            var rEC_MNOParameter = rEC_MNO != null ?
                new ObjectParameter("REC_MNO", rEC_MNO) :
                new ObjectParameter("REC_MNO", typeof(string));
    
            var rECIN_UTCParameter = rECIN_UTC.HasValue ?
                new ObjectParameter("RECIN_UTC", rECIN_UTC) :
                new ObjectParameter("RECIN_UTC", typeof(System.DateTime));
    
            var dISPATCHParameter = dISPATCH != null ?
                new ObjectParameter("DISPATCH", dISPATCH) :
                new ObjectParameter("DISPATCH", typeof(string));
    
            var dISPATCH_CONParameter = dISPATCH_CON != null ?
                new ObjectParameter("DISPATCH_CON", dISPATCH_CON) :
                new ObjectParameter("DISPATCH_CON", typeof(string));
    
            var rECEIVINGParameter = rECEIVING != null ?
                new ObjectParameter("RECEIVING", rECEIVING) :
                new ObjectParameter("RECEIVING", typeof(string));
    
            var rECEIVING_CONParameter = rECEIVING_CON != null ?
                new ObjectParameter("RECEIVING_CON", rECEIVING_CON) :
                new ObjectParameter("RECEIVING_CON", typeof(string));
    
            var dEST_NAMEParameter = dEST_NAME != null ?
                new ObjectParameter("DEST_NAME", dEST_NAME) :
                new ObjectParameter("DEST_NAME", typeof(string));
    
            var gOODS_NAMEParameter = gOODS_NAME != null ?
                new ObjectParameter("GOODS_NAME", gOODS_NAME) :
                new ObjectParameter("GOODS_NAME", typeof(string));
    
            var qTYParameter = qTY.HasValue ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(int));
    
            var qTY_WEIGHTParameter = qTY_WEIGHT.HasValue ?
                new ObjectParameter("QTY_WEIGHT", qTY_WEIGHT) :
                new ObjectParameter("QTY_WEIGHT", typeof(decimal));
    
            var qTY_VOLUMEParameter = qTY_VOLUME.HasValue ?
                new ObjectParameter("QTY_VOLUME", qTY_VOLUME) :
                new ObjectParameter("QTY_VOLUME", typeof(decimal));
    
            var qTY_NUMBERParameter = qTY_NUMBER.HasValue ?
                new ObjectParameter("QTY_NUMBER", qTY_NUMBER) :
                new ObjectParameter("QTY_NUMBER", typeof(int));
    
            var rEMARKParameter = rEMARK != null ?
                new ObjectParameter("REMARK", rEMARK) :
                new ObjectParameter("REMARK", typeof(string));
    
            var cRT_USERParameter = cRT_USER != null ?
                new ObjectParameter("CRT_USER", cRT_USER) :
                new ObjectParameter("CRT_USER", typeof(string));
    
            var directPrintParameter = directPrint.HasValue ?
                new ObjectParameter("DirectPrint", directPrint) :
                new ObjectParameter("DirectPrint", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_AddReciveForm2", rEC_MNOParameter, rECIN_UTCParameter, dISPATCHParameter, dISPATCH_CONParameter, rECEIVINGParameter, rECEIVING_CONParameter, dEST_NAMEParameter, gOODS_NAMEParameter, qTYParameter, qTY_WEIGHTParameter, qTY_VOLUMEParameter, qTY_NUMBERParameter, rEMARKParameter, cRT_USERParameter, directPrintParameter);
        }
    
        public virtual int GRP_AddReciveFormLabelPrint(string rEC_ID, Nullable<int> sTART_NUM, Nullable<int> eND_NUM, string cRT_USER)
        {
            var rEC_IDParameter = rEC_ID != null ?
                new ObjectParameter("REC_ID", rEC_ID) :
                new ObjectParameter("REC_ID", typeof(string));
    
            var sTART_NUMParameter = sTART_NUM.HasValue ?
                new ObjectParameter("START_NUM", sTART_NUM) :
                new ObjectParameter("START_NUM", typeof(int));
    
            var eND_NUMParameter = eND_NUM.HasValue ?
                new ObjectParameter("END_NUM", eND_NUM) :
                new ObjectParameter("END_NUM", typeof(int));
    
            var cRT_USERParameter = cRT_USER != null ?
                new ObjectParameter("CRT_USER", cRT_USER) :
                new ObjectParameter("CRT_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_AddReciveFormLabelPrint", rEC_IDParameter, sTART_NUMParameter, eND_NUMParameter, cRT_USERParameter);
        }
    
        public virtual int GRP_AddShipping(ObjectParameter sPM_ID, string cRT_USER)
        {
            var cRT_USERParameter = cRT_USER != null ?
                new ObjectParameter("CRT_USER", cRT_USER) :
                new ObjectParameter("CRT_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_AddShipping", sPM_ID, cRT_USERParameter);
        }
    
        public virtual int GRP_AddShippingItem(string sPM_ID, string rEC_ID, string cRT_USER)
        {
            var sPM_IDParameter = sPM_ID != null ?
                new ObjectParameter("SPM_ID", sPM_ID) :
                new ObjectParameter("SPM_ID", typeof(string));
    
            var rEC_IDParameter = rEC_ID != null ?
                new ObjectParameter("REC_ID", rEC_ID) :
                new ObjectParameter("REC_ID", typeof(string));
    
            var cRT_USERParameter = cRT_USER != null ?
                new ObjectParameter("CRT_USER", cRT_USER) :
                new ObjectParameter("CRT_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_AddShippingItem", sPM_IDParameter, rEC_IDParameter, cRT_USERParameter);
        }
    
        public virtual ObjectResult<GRP_GetPrintLabels_Result> GRP_GetPrintLabels(string uSER_NO)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRP_GetPrintLabels_Result>("GRP_GetPrintLabels", uSER_NOParameter);
        }
    
        public virtual int GRP_GetSerialNo(string tABLE_NA, string pK_YYYY, string pK_MM, string pK_DD, string pK_STR1, ObjectParameter nEW_SEQ)
        {
            var tABLE_NAParameter = tABLE_NA != null ?
                new ObjectParameter("TABLE_NA", tABLE_NA) :
                new ObjectParameter("TABLE_NA", typeof(string));
    
            var pK_YYYYParameter = pK_YYYY != null ?
                new ObjectParameter("PK_YYYY", pK_YYYY) :
                new ObjectParameter("PK_YYYY", typeof(string));
    
            var pK_MMParameter = pK_MM != null ?
                new ObjectParameter("PK_MM", pK_MM) :
                new ObjectParameter("PK_MM", typeof(string));
    
            var pK_DDParameter = pK_DD != null ?
                new ObjectParameter("PK_DD", pK_DD) :
                new ObjectParameter("PK_DD", typeof(string));
    
            var pK_STR1Parameter = pK_STR1 != null ?
                new ObjectParameter("PK_STR1", pK_STR1) :
                new ObjectParameter("PK_STR1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_GetSerialNo", tABLE_NAParameter, pK_YYYYParameter, pK_MMParameter, pK_DDParameter, pK_STR1Parameter, nEW_SEQ);
        }
    
        public virtual int GRP_GetSerialNo_Monthly(string tABLE_NA, Nullable<System.DateTime> tRANS_DATE, string pK_STR1, ObjectParameter nEW_SEQ)
        {
            var tABLE_NAParameter = tABLE_NA != null ?
                new ObjectParameter("TABLE_NA", tABLE_NA) :
                new ObjectParameter("TABLE_NA", typeof(string));
    
            var tRANS_DATEParameter = tRANS_DATE.HasValue ?
                new ObjectParameter("TRANS_DATE", tRANS_DATE) :
                new ObjectParameter("TRANS_DATE", typeof(System.DateTime));
    
            var pK_STR1Parameter = pK_STR1 != null ?
                new ObjectParameter("PK_STR1", pK_STR1) :
                new ObjectParameter("PK_STR1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_GetSerialNo_Monthly", tABLE_NAParameter, tRANS_DATEParameter, pK_STR1Parameter, nEW_SEQ);
        }
    
        public virtual ObjectResult<GRP_GetShippingItems_Result> GRP_GetShippingItems(string sPM_ID)
        {
            var sPM_IDParameter = sPM_ID != null ?
                new ObjectParameter("SPM_ID", sPM_ID) :
                new ObjectParameter("SPM_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRP_GetShippingItems_Result>("GRP_GetShippingItems", sPM_IDParameter);
        }
    
        public virtual int GRP_ModifyReciveForm(string rEC_ID, string rEC_MNO, Nullable<System.DateTime> rECIN_UTC, string dISPATCH, string dISPATCH_CON, string rECEIVING, string rECEIVING_CON, string dEST_NAME, string gOODS_NAME, Nullable<int> qTY, Nullable<decimal> qTY_WEIGHT, Nullable<decimal> qTY_VOLUME, Nullable<int> qTY_NUMBER, string rEMARK, string mOD_USER)
        {
            var rEC_IDParameter = rEC_ID != null ?
                new ObjectParameter("REC_ID", rEC_ID) :
                new ObjectParameter("REC_ID", typeof(string));
    
            var rEC_MNOParameter = rEC_MNO != null ?
                new ObjectParameter("REC_MNO", rEC_MNO) :
                new ObjectParameter("REC_MNO", typeof(string));
    
            var rECIN_UTCParameter = rECIN_UTC.HasValue ?
                new ObjectParameter("RECIN_UTC", rECIN_UTC) :
                new ObjectParameter("RECIN_UTC", typeof(System.DateTime));
    
            var dISPATCHParameter = dISPATCH != null ?
                new ObjectParameter("DISPATCH", dISPATCH) :
                new ObjectParameter("DISPATCH", typeof(string));
    
            var dISPATCH_CONParameter = dISPATCH_CON != null ?
                new ObjectParameter("DISPATCH_CON", dISPATCH_CON) :
                new ObjectParameter("DISPATCH_CON", typeof(string));
    
            var rECEIVINGParameter = rECEIVING != null ?
                new ObjectParameter("RECEIVING", rECEIVING) :
                new ObjectParameter("RECEIVING", typeof(string));
    
            var rECEIVING_CONParameter = rECEIVING_CON != null ?
                new ObjectParameter("RECEIVING_CON", rECEIVING_CON) :
                new ObjectParameter("RECEIVING_CON", typeof(string));
    
            var dEST_NAMEParameter = dEST_NAME != null ?
                new ObjectParameter("DEST_NAME", dEST_NAME) :
                new ObjectParameter("DEST_NAME", typeof(string));
    
            var gOODS_NAMEParameter = gOODS_NAME != null ?
                new ObjectParameter("GOODS_NAME", gOODS_NAME) :
                new ObjectParameter("GOODS_NAME", typeof(string));
    
            var qTYParameter = qTY.HasValue ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(int));
    
            var qTY_WEIGHTParameter = qTY_WEIGHT.HasValue ?
                new ObjectParameter("QTY_WEIGHT", qTY_WEIGHT) :
                new ObjectParameter("QTY_WEIGHT", typeof(decimal));
    
            var qTY_VOLUMEParameter = qTY_VOLUME.HasValue ?
                new ObjectParameter("QTY_VOLUME", qTY_VOLUME) :
                new ObjectParameter("QTY_VOLUME", typeof(decimal));
    
            var qTY_NUMBERParameter = qTY_NUMBER.HasValue ?
                new ObjectParameter("QTY_NUMBER", qTY_NUMBER) :
                new ObjectParameter("QTY_NUMBER", typeof(int));
    
            var rEMARKParameter = rEMARK != null ?
                new ObjectParameter("REMARK", rEMARK) :
                new ObjectParameter("REMARK", typeof(string));
    
            var mOD_USERParameter = mOD_USER != null ?
                new ObjectParameter("MOD_USER", mOD_USER) :
                new ObjectParameter("MOD_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_ModifyReciveForm", rEC_IDParameter, rEC_MNOParameter, rECIN_UTCParameter, dISPATCHParameter, dISPATCH_CONParameter, rECEIVINGParameter, rECEIVING_CONParameter, dEST_NAMEParameter, gOODS_NAMEParameter, qTYParameter, qTY_WEIGHTParameter, qTY_VOLUMEParameter, qTY_NUMBERParameter, rEMARKParameter, mOD_USERParameter);
        }
    
        public virtual ObjectResult<GRP_QueryItemsToCollect_Result> GRP_QueryItemsToCollect(string uSER_NO)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRP_QueryItemsToCollect_Result>("GRP_QueryItemsToCollect", uSER_NOParameter);
        }
    
        public virtual ObjectResult<GRP_QueryMainForm_Result> GRP_QueryMainForm(string uSER_NO)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GRP_QueryMainForm_Result>("GRP_QueryMainForm", uSER_NOParameter);
        }
    
        public virtual int GRP_RemoveShippingItem(string sPM_ID, string rEC_ID)
        {
            var sPM_IDParameter = sPM_ID != null ?
                new ObjectParameter("SPM_ID", sPM_ID) :
                new ObjectParameter("SPM_ID", typeof(string));
    
            var rEC_IDParameter = rEC_ID != null ?
                new ObjectParameter("REC_ID", rEC_ID) :
                new ObjectParameter("REC_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GRP_RemoveShippingItem", sPM_IDParameter, rEC_IDParameter);
        }
    
        public virtual int PRP_AddReciveForm(string rEC_MNO, Nullable<System.DateTime> rECIN_UTC, string dISPATCH, string dISPATCH_CON, string rECEIVING, string rECEIVING_CON, string dEST_NAME, string gOODS_NAME, Nullable<int> qTY, Nullable<decimal> qTY_WEIGHT, Nullable<decimal> qTY_VOLUME, Nullable<int> qTY_NUMBER, string rEMARK, string cRT_USER)
        {
            var rEC_MNOParameter = rEC_MNO != null ?
                new ObjectParameter("REC_MNO", rEC_MNO) :
                new ObjectParameter("REC_MNO", typeof(string));
    
            var rECIN_UTCParameter = rECIN_UTC.HasValue ?
                new ObjectParameter("RECIN_UTC", rECIN_UTC) :
                new ObjectParameter("RECIN_UTC", typeof(System.DateTime));
    
            var dISPATCHParameter = dISPATCH != null ?
                new ObjectParameter("DISPATCH", dISPATCH) :
                new ObjectParameter("DISPATCH", typeof(string));
    
            var dISPATCH_CONParameter = dISPATCH_CON != null ?
                new ObjectParameter("DISPATCH_CON", dISPATCH_CON) :
                new ObjectParameter("DISPATCH_CON", typeof(string));
    
            var rECEIVINGParameter = rECEIVING != null ?
                new ObjectParameter("RECEIVING", rECEIVING) :
                new ObjectParameter("RECEIVING", typeof(string));
    
            var rECEIVING_CONParameter = rECEIVING_CON != null ?
                new ObjectParameter("RECEIVING_CON", rECEIVING_CON) :
                new ObjectParameter("RECEIVING_CON", typeof(string));
    
            var dEST_NAMEParameter = dEST_NAME != null ?
                new ObjectParameter("DEST_NAME", dEST_NAME) :
                new ObjectParameter("DEST_NAME", typeof(string));
    
            var gOODS_NAMEParameter = gOODS_NAME != null ?
                new ObjectParameter("GOODS_NAME", gOODS_NAME) :
                new ObjectParameter("GOODS_NAME", typeof(string));
    
            var qTYParameter = qTY.HasValue ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(int));
    
            var qTY_WEIGHTParameter = qTY_WEIGHT.HasValue ?
                new ObjectParameter("QTY_WEIGHT", qTY_WEIGHT) :
                new ObjectParameter("QTY_WEIGHT", typeof(decimal));
    
            var qTY_VOLUMEParameter = qTY_VOLUME.HasValue ?
                new ObjectParameter("QTY_VOLUME", qTY_VOLUME) :
                new ObjectParameter("QTY_VOLUME", typeof(decimal));
    
            var qTY_NUMBERParameter = qTY_NUMBER.HasValue ?
                new ObjectParameter("QTY_NUMBER", qTY_NUMBER) :
                new ObjectParameter("QTY_NUMBER", typeof(int));
    
            var rEMARKParameter = rEMARK != null ?
                new ObjectParameter("REMARK", rEMARK) :
                new ObjectParameter("REMARK", typeof(string));
    
            var cRT_USERParameter = cRT_USER != null ?
                new ObjectParameter("CRT_USER", cRT_USER) :
                new ObjectParameter("CRT_USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRP_AddReciveForm", rEC_MNOParameter, rECIN_UTCParameter, dISPATCHParameter, dISPATCH_CONParameter, rECEIVINGParameter, rECEIVING_CONParameter, dEST_NAMEParameter, gOODS_NAMEParameter, qTYParameter, qTY_WEIGHTParameter, qTY_VOLUMEParameter, qTY_NUMBERParameter, rEMARKParameter, cRT_USERParameter);
        }
    
        public virtual int SysCore_Auth_CreateUserFromHR(string lOGIN_ID, ObjectParameter uSER_NO)
        {
            var lOGIN_IDParameter = lOGIN_ID != null ?
                new ObjectParameter("LOGIN_ID", lOGIN_ID) :
                new ObjectParameter("LOGIN_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SysCore_Auth_CreateUserFromHR", lOGIN_IDParameter, uSER_NO);
        }
    
        public virtual ObjectResult<SysCore_Auth_GetActionsByUser_Result> SysCore_Auth_GetActionsByUser(string uSER_NO, string pRG_AREA, string mVC_CTRL)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var pRG_AREAParameter = pRG_AREA != null ?
                new ObjectParameter("PRG_AREA", pRG_AREA) :
                new ObjectParameter("PRG_AREA", typeof(string));
    
            var mVC_CTRLParameter = mVC_CTRL != null ?
                new ObjectParameter("MVC_CTRL", mVC_CTRL) :
                new ObjectParameter("MVC_CTRL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SysCore_Auth_GetActionsByUser_Result>("SysCore_Auth_GetActionsByUser", uSER_NOParameter, pRG_AREAParameter, mVC_CTRLParameter);
        }
    
        public virtual ObjectResult<SysCore_Auth_GetLoginInfo_Result> SysCore_Auth_GetLoginInfo(string lOGIN_ID)
        {
            var lOGIN_IDParameter = lOGIN_ID != null ?
                new ObjectParameter("LOGIN_ID", lOGIN_ID) :
                new ObjectParameter("LOGIN_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SysCore_Auth_GetLoginInfo_Result>("SysCore_Auth_GetLoginInfo", lOGIN_IDParameter);
        }
    
        public virtual ObjectResult<SysCore_Auth_GetMenuByUser_Result> SysCore_Auth_GetMenuByUser(string uSER_NO, string pRG_AREA)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var pRG_AREAParameter = pRG_AREA != null ?
                new ObjectParameter("PRG_AREA", pRG_AREA) :
                new ObjectParameter("PRG_AREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SysCore_Auth_GetMenuByUser_Result>("SysCore_Auth_GetMenuByUser", uSER_NOParameter, pRG_AREAParameter);
        }
    
        public virtual ObjectResult<SysCore_Auth_GetModuleByUser_Result> SysCore_Auth_GetModuleByUser(string uSER_NO)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SysCore_Auth_GetModuleByUser_Result>("SysCore_Auth_GetModuleByUser", uSER_NOParameter);
        }
    
        public virtual ObjectResult<SysCore_Auth_GetUserInfo_Result> SysCore_Auth_GetUserInfo(string uSER_NO)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SysCore_Auth_GetUserInfo_Result>("SysCore_Auth_GetUserInfo", uSER_NOParameter);
        }
    
        public virtual ObjectResult<SysCore_Auth_VerifyWebFormByUser_Result> SysCore_Auth_VerifyWebFormByUser(string uSER_NO, string eNT_POINT)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var eNT_POINTParameter = eNT_POINT != null ?
                new ObjectParameter("ENT_POINT", eNT_POINT) :
                new ObjectParameter("ENT_POINT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SysCore_Auth_VerifyWebFormByUser_Result>("SysCore_Auth_VerifyWebFormByUser", uSER_NOParameter, eNT_POINTParameter);
        }
    }
}
