//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRP_BS_GOODSTYPE
    {
        public string GDSTYPE_ID { get; set; }
        public string CNTYPE_ID { get; set; }
        public string GDSTYPE_NAME { get; set; }
        public string DESCTXT { get; set; }
        public string ENABLED { get; set; }
    
        public virtual GRP_BS_CONTAINERTYPE GRP_BS_CONTAINERTYPE { get; set; }
    }
}
