//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRPREC_PRT
    {
        public System.DateTime CRT_UTC { get; set; }
        public string REC_ID { get; set; }
        public Nullable<int> START_NUM { get; set; }
        public Nullable<int> END_NUM { get; set; }
        public string IS_PRINT { get; set; }
        public string CRT_USER { get; set; }
        public Nullable<System.DateTime> MOD_UTC { get; set; }
    }
}
