//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOKS> BOOKS { get; set; }
        public virtual DbSet<GRP_BS_CONTAINERTYPE> GRP_BS_CONTAINERTYPE { get; set; }
        public virtual DbSet<GRP_BS_GOODSTYPE> GRP_BS_GOODSTYPE { get; set; }
        public virtual DbSet<GRP_BS_NOTE> GRP_BS_NOTE { get; set; }
        public virtual DbSet<GRP_BS_SEQ> GRP_BS_SEQ { get; set; }
        public virtual DbSet<GRP_BS_SPMRK> GRP_BS_SPMRK { get; set; }
        public virtual DbSet<GRP_BS_TAG> GRP_BS_TAG { get; set; }
        public virtual DbSet<GRP_BS_WHE> GRP_BS_WHE { get; set; }
        public virtual DbSet<GRPCONTACT> GRPCONTACT { get; set; }
        public virtual DbSet<GRPCUST> GRPCUST { get; set; }
        public virtual DbSet<GRPFILES> GRPFILES { get; set; }
        public virtual DbSet<GRPMAD> GRPMAD { get; set; }
        public virtual DbSet<GRPMAH> GRPMAH { get; set; }
        public virtual DbSet<GRPMAH_CO_STATUS> GRPMAH_CO_STATUS { get; set; }
        public virtual DbSet<GRPREC> GRPREC { get; set; }
        public virtual DbSet<GRPREC_PRT> GRPREC_PRT { get; set; }
        public virtual DbSet<SYSCKIND> SYSCKIND { get; set; }
        public virtual DbSet<SYSCODE> SYSCODE { get; set; }
        public virtual DbSet<SYSCOMP> SYSCOMP { get; set; }
        public virtual DbSet<SYSDEPT> SYSDEPT { get; set; }
        public virtual DbSet<SYSPACK> SYSPACK { get; set; }
        public virtual DbSet<SYSPRG> SYSPRG { get; set; }
        public virtual DbSet<SYSPROFILE> SYSPROFILE { get; set; }
        public virtual DbSet<SYSROLE> SYSROLE { get; set; }
        public virtual DbSet<SYSROLE_FUN> SYSROLE_FUN { get; set; }
        public virtual DbSet<SYSUSER> SYSUSER { get; set; }
        public virtual DbSet<SYSUSER_EVNTLOG> SYSUSER_EVNTLOG { get; set; }
    }
}
