//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPRG
    {
        public SYSPRG()
        {
            this.SYSROLE_FUN = new HashSet<SYSROLE_FUN>();
        }
    
        public string PRG_NO { get; set; }
        public string PRG_NAME { get; set; }
        public string PRG_TYPE { get; set; }
        public string PRG_AREA { get; set; }
        public string MVC_CTRL { get; set; }
        public string MVC_ACT { get; set; }
        public string ENT_POINT { get; set; }
        public string PARAM_VAL { get; set; }
        public int ORDERNUM { get; set; }
        public string IS_MENU { get; set; }
        public string UP_DIRNO { get; set; }
        public string ENABLED { get; set; }
    
        public virtual ICollection<SYSROLE_FUN> SYSROLE_FUN { get; set; }
    }
}
