//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSROLE
    {
        public SYSROLE()
        {
            this.SYSROLE_FUN = new HashSet<SYSROLE_FUN>();
            this.SYSUSER = new HashSet<SYSUSER>();
        }
    
        public string ROLE_NO { get; set; }
        public string ROLE_NAME { get; set; }
    
        public virtual ICollection<SYSROLE_FUN> SYSROLE_FUN { get; set; }
        public virtual ICollection<SYSUSER> SYSUSER { get; set; }
    }
}
