//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSUSER_EVNTLOG
    {
        public int EVNT_ID { get; set; }
        public string USER_NO { get; set; }
        public string PRG_AREA { get; set; }
        public string MVC_CTRL { get; set; }
        public string MVC_ACT { get; set; }
        public string DESCTXT { get; set; }
        public Nullable<System.DateTime> CRT_UTC { get; set; }
        public string HOST_IPADDR { get; set; }
        public string POST_DATA { get; set; }
    }
}
